
const comercioprefix = '/api/comercio';
const contableprefix = '/api/contable';

let module = {
    comercio: {
        compra:        comercioprefix + '/compra',
        venta:         comercioprefix + '/venta',
        inventario:    comercioprefix + '/inventario',
        configuracion: comercioprefix + '/configuracion',
    },
    contabilidad: {},
    configuracion: '/api/configuracion',
};

const webservices = {

    wsconfiguracionmoneda_index:      module.configuracion + '/moneda/index',
    wsconfiguracionmoneda_create:     module.configuracion + '/moneda/create',
    wsconfiguracionmoneda_store:      module.configuracion + '/moneda/store',
    wsconfiguracionmoneda_store:      module.configuracion + '/moneda/editar',
    wsconfiguracionmoneda_update:     module.configuracion + '/moneda/update',
    wsconfiguracionmoneda_update:     module.configuracion + '/moneda/show',
    wsconfiguracionmoneda_delete:     module.configuracion + '/moneda/delete',
    wsconfiguracionmoneda_reporte:    module.configuracion + '/moneda/reporte',
    wsconfiguracionmoneda_searchByID: module.configuracion + '/moneda/searchByID',


    wscomercioinventariociudadclasificacion_index:      module.comercio.inventario + '/ciudadclasificacion/index',
    wscomercioinventariociudadclasificacion_create:     module.comercio.inventario + '/ciudadclasificacion/create',
    wscomercioinventariociudadclasificacion_store:      module.comercio.inventario + '/ciudadclasificacion/store',
    wscomercioinventariociudadclasificacion_update:     module.comercio.inventario + '/ciudadclasificacion/update',
    wscomercioinventariociudadclasificacion_delete:     module.comercio.inventario + '/ciudadclasificacion/delete',
    wscomercioinventariociudadclasificacion_reporte:    module.comercio.inventario + '/ciudadclasificacion/reporte',
    wscomercioinventariociudadclasificacion_searchByID: module.comercio.inventario + '/ciudadclasificacion/searchByID',

    wscomercioinventariociudad_index:      module.comercio.inventario + '/ciudad/index',
    wscomercioinventariociudad_create:     module.comercio.inventario + '/ciudad/create',
    wscomercioinventariociudad_store:      module.comercio.inventario + '/ciudad/store',
    wscomercioinventariociudad_editar:     module.comercio.inventario + '/ciudad/editar',
    wscomercioinventariociudad_update:     module.comercio.inventario + '/ciudad/update',
    wscomercioinventariociudad_show:       module.comercio.inventario + '/ciudad/show',
    wscomercioinventariociudad_delete:     module.comercio.inventario + '/ciudad/delete',
    wscomercioinventariociudad_reporte:    module.comercio.inventario + '/ciudad/reporte',
    wscomercioinventariociudad_searchByID: module.comercio.inventario + '/ciudad/searchByID',

    wscomercioinventarioseccioninventario_index:      module.comercio.inventario + '/seccioninventario/index',
    wscomercioinventarioseccioninventario_create:     module.comercio.inventario + '/seccioninventario/create',
    wscomercioinventarioseccioninventario_store:      module.comercio.inventario + '/seccioninventario/store',
    wscomercioinventarioseccioninventario_update:     module.comercio.inventario + '/seccioninventario/update',
    wscomercioinventarioseccioninventario_delete:     module.comercio.inventario + '/seccioninventario/delete',
    wscomercioinventarioseccioninventario_reporte:    module.comercio.inventario + '/seccioninventario/reporte',
    wscomercioinventarioseccioninventario_searchByID: module.comercio.inventario + '/seccioninventario/searchByID',

    wscomercioinventarioproductotipo_index:      module.comercio.inventario + '/productotipo/index',
    wscomercioinventarioproductotipo_create:     module.comercio.inventario + '/productotipo/create',
    wscomercioinventarioproductotipo_store:      module.comercio.inventario + '/productotipo/store',
    wscomercioinventarioproductotipo_update:     module.comercio.inventario + '/productotipo/update',
    wscomercioinventarioproductotipo_delete:     module.comercio.inventario + '/productotipo/delete',
    wscomercioinventarioproductotipo_reporte:    module.comercio.inventario + '/productotipo/reporte',
    wscomercioinventarioproductotipo_searchByID: module.comercio.inventario + '/productotipo/searchByID',

    wscomercioinventarioproductomarca_index:      module.comercio.inventario + '/productomarca/index',
    wscomercioinventarioproductomarca_create:     module.comercio.inventario + '/productomarca/create',
    wscomercioinventarioproductomarca_store:      module.comercio.inventario + '/productomarca/store',
    wscomercioinventarioproductomarca_update:     module.comercio.inventario + '/productomarca/update',
    wscomercioinventarioproductomarca_delete:     module.comercio.inventario + '/productomarca/delete',
    wscomercioinventarioproductomarca_reporte:    module.comercio.inventario + '/productomarca/reporte',
    wscomercioinventarioproductomarca_searchByID: module.comercio.inventario + '/productomarca/searchByID',

    wscomercioinventarioproductogrupo_index:      module.comercio.inventario + '/productogrupo/index',
    wscomercioinventarioproductogrupo_create:     module.comercio.inventario + '/productogrupo/create',
    wscomercioinventarioproductogrupo_store:      module.comercio.inventario + '/productogrupo/store',
    wscomercioinventarioproductogrupo_update:     module.comercio.inventario + '/productogrupo/update',
    wscomercioinventarioproductogrupo_delete:     module.comercio.inventario + '/productogrupo/delete',
    wscomercioinventarioproductogrupo_reporte:    module.comercio.inventario + '/productogrupo/reporte',
    wscomercioinventarioproductogrupo_searchByID: module.comercio.inventario + '/productogrupo/searchByID',

    wscomercioinventarioproductosubgrupo_index:      module.comercio.inventario + '/productosubgrupo/index',
    wscomercioinventarioproductosubgrupo_create:     module.comercio.inventario + '/productosubgrupo/create',
    wscomercioinventarioproductosubgrupo_store:      module.comercio.inventario + '/productosubgrupo/store',
    wscomercioinventarioproductosubgrupo_update:     module.comercio.inventario + '/productosubgrupo/update',
    wscomercioinventarioproductosubgrupo_delete:     module.comercio.inventario + '/productosubgrupo/delete',
    wscomercioinventarioproductosubgrupo_reporte:    module.comercio.inventario + '/productosubgrupo/reporte',
    wscomercioinventarioproductosubgrupo_searchByID: module.comercio.inventario + '/productosubgrupo/searchByID',

    wscomercioinventariocategoria_index:      module.comercio.inventario + '/categoria/index',
    wscomercioinventariocategoria_create:     module.comercio.inventario + '/categoria/create',
    wscomercioinventariocategoria_store:      module.comercio.inventario + '/categoria/store',
    wscomercioinventariocategoria_update:     module.comercio.inventario + '/categoria/update',
    wscomercioinventariocategoria_delete:     module.comercio.inventario + '/categoria/delete',
    wscomercioinventariocategoria_reporte:    module.comercio.inventario + '/categoria/reporte',
    wscomercioinventariocategoria_searchByID: module.comercio.inventario + '/categoria/searchByID',

    wscomercioinventariounidadmedida_index:      module.comercio.inventario + '/unidadmedida/index',
    wscomercioinventariounidadmedida_create:     module.comercio.inventario + '/unidadmedida/create',
    wscomercioinventariounidadmedida_store:      module.comercio.inventario + '/unidadmedida/store',
    wscomercioinventariounidadmedida_update:     module.comercio.inventario + '/unidadmedida/update',
    wscomercioinventariounidadmedida_delete:     module.comercio.inventario + '/unidadmedida/delete',
    wscomercioinventariounidadmedida_reporte:    module.comercio.inventario + '/unidadmedida/reporte',
    wscomercioinventariounidadmedida_searchByID: module.comercio.inventario + '/unidadmedida/searchByID',

    wscomercioinventarioconceptoinventario_index:      module.comercio.inventario + '/conceptoinventario/index',
    wscomercioinventarioconceptoinventario_create:     module.comercio.inventario + '/conceptoinventario/create',
    wscomercioinventarioconceptoinventario_store:      module.comercio.inventario + '/conceptoinventario/store',
    wscomercioinventarioconceptoinventario_editar:     module.comercio.inventario + '/conceptoinventario/editar',
    wscomercioinventarioconceptoinventario_update:     module.comercio.inventario + '/conceptoinventario/update',
    wscomercioinventarioconceptoinventario_show:       module.comercio.inventario + '/conceptoinventario/show',
    wscomercioinventarioconceptoinventario_delete:     module.comercio.inventario + '/conceptoinventario/delete',
    wscomercioinventarioconceptoinventario_reporte:    module.comercio.inventario + '/conceptoinventario/reporte',
    wscomercioinventarioconceptoinventario_searchByID: module.comercio.inventario + '/conceptoinventario/searchByID',

    wscomercioinventarioalmacen_index:      module.comercio.inventario + '/almacen/index',
    wscomercioinventarioalmacen_create:     module.comercio.inventario + '/almacen/create',
    wscomercioinventarioalmacen_store:      module.comercio.inventario + '/almacen/store',
    wscomercioinventarioalmacen_editar:     module.comercio.inventario + '/almacen/editar',
    wscomercioinventarioalmacen_update:     module.comercio.inventario + '/almacen/update',
    wscomercioinventarioalmacen_show:       module.comercio.inventario + '/almacen/show',
    wscomercioinventarioalmacen_delete:     module.comercio.inventario + '/almacen/delete',
    wscomercioinventarioalmacen_reporte:    module.comercio.inventario + '/almacen/reporte',
    wscomercioinventarioalmacen_searchByID: module.comercio.inventario + '/almacen/searchByID',

    wscomercioinventarioproducto_index:      module.comercio.inventario + '/producto/index',
    wscomercioinventarioproducto_create:     module.comercio.inventario + '/producto/create',
    wscomercioinventarioproducto_store:      module.comercio.inventario + '/producto/store',
    wscomercioinventarioproducto_editar:     module.comercio.inventario + '/producto/editar',
    wscomercioinventarioproducto_update:     module.comercio.inventario + '/producto/update',
    wscomercioinventarioproducto_show:       module.comercio.inventario + '/producto/show',
    wscomercioinventarioproducto_delete:     module.comercio.inventario + '/producto/delete',
    wscomercioinventarioproducto_reporte:    module.comercio.inventario + '/producto/reporte',
    wscomercioinventarioproducto_searchByID: module.comercio.inventario + '/producto/searchByID',


    wscomercioinventariounidadmedidaproducto_index:      module.comercio.inventario + '/unidadmedidaproducto/index',


    wscomercioinventarionotaingreso_index:      module.comercio.inventario + '/notaingreso/index',
    wscomercioinventarionotaingreso_create:     module.comercio.inventario + '/notaingreso/create',
    wscomercioinventarionotaingreso_store:      module.comercio.inventario + '/notaingreso/store',
    wscomercioinventarionotaingreso_editar:     module.comercio.inventario + '/notaingreso/editar',
    wscomercioinventarionotaingreso_update:     module.comercio.inventario + '/notaingreso/update',
    wscomercioinventarionotaingreso_show:       module.comercio.inventario + '/notaingreso/show',
    wscomercioinventarionotaingreso_delete:     module.comercio.inventario + '/notaingreso/delete',
    wscomercioinventarionotaingreso_reporte:    module.comercio.inventario + '/notaingreso/reporte',
    wscomercioinventarionotaingreso_searchByID: module.comercio.inventario + '/notaingreso/searchByID',



    wscomercioventaunionsucursal_index:      module.comercio.venta + '/unionsucursal/index',
    wscomercioventaunionsucursal_create:     module.comercio.venta + '/unionsucursal/create',
    wscomercioventaunionsucursal_store:      module.comercio.venta + '/unionsucursal/store',
    wscomercioventaunionsucursal_editar:     module.comercio.venta + '/unionsucursal/editar',
    wscomercioventaunionsucursal_update:     module.comercio.venta + '/unionsucursal/update',
    wscomercioventaunionsucursal_show:       module.comercio.venta + '/unionsucursal/show',
    wscomercioventaunionsucursal_delete:     module.comercio.venta + '/unionsucursal/delete',
    wscomercioventaunionsucursal_reporte:    module.comercio.venta + '/unionsucursal/reporte',
    wscomercioventaunionsucursal_searchByID: module.comercio.venta + '/unionsucursal/searchByID',

    wscomercioventasucursal_index:      module.comercio.venta + '/sucursal/index',
    wscomercioventasucursal_create:     module.comercio.venta + '/sucursal/create',
    wscomercioventasucursal_store:      module.comercio.venta + '/sucursal/store',
    wscomercioventasucursal_editar:     module.comercio.venta + '/sucursal/editar',
    wscomercioventasucursal_update:     module.comercio.venta + '/sucursal/update',
    wscomercioventasucursal_show:       module.comercio.venta + '/sucursal/show',
    wscomercioventasucursal_delete:     module.comercio.venta + '/sucursal/delete',
    wscomercioventasucursal_reporte:    module.comercio.venta + '/sucursal/reporte',
    wscomercioventasucursal_searchByID: module.comercio.venta + '/sucursal/searchByID',

    wscomercioventalistaprecio_index:      module.comercio.venta + '/listaprecio/index',
    wscomercioventalistaprecio_create:     module.comercio.venta + '/listaprecio/create',
    wscomercioventalistaprecio_store:      module.comercio.venta + '/listaprecio/store',
    wscomercioventalistaprecio_editar:     module.comercio.venta + '/listaprecio/editar',
    wscomercioventalistaprecio_update:     module.comercio.venta + '/listaprecio/update',
    wscomercioventalistaprecio_show:       module.comercio.venta + '/listaprecio/show',
    wscomercioventalistaprecio_delete:     module.comercio.venta + '/listaprecio/delete',
    wscomercioventalistaprecio_reporte:    module.comercio.venta + '/listaprecio/reporte',
    wscomercioventalistaprecio_searchByID: module.comercio.venta + '/listaprecio/searchByID',

    wscomercioventaconceptoventa_index:      module.comercio.venta + '/conceptoventa/index',
    wscomercioventaconceptoventa_create:     module.comercio.venta + '/conceptoventa/create',
    wscomercioventaconceptoventa_store:      module.comercio.venta + '/conceptoventa/store',
    wscomercioventaconceptoventa_editar:     module.comercio.venta + '/conceptoventa/editar',
    wscomercioventaconceptoventa_update:     module.comercio.venta + '/conceptoventa/update',
    wscomercioventaconceptoventa_show:       module.comercio.venta + '/conceptoventa/show',
    wscomercioventaconceptoventa_delete:     module.comercio.venta + '/conceptoventa/delete',
    wscomercioventaconceptoventa_reporte:    module.comercio.venta + '/conceptoventa/reporte',
    wscomercioventaconceptoventa_searchByID: module.comercio.venta + '/conceptoventa/searchByID',

    wscomercioventaclientetipo_index:      module.comercio.venta + '/clientetipo/index',
    wscomercioventaclientetipo_create:     module.comercio.venta + '/clientetipo/create',
    wscomercioventaclientetipo_store:      module.comercio.venta + '/clientetipo/store',
    wscomercioventaclientetipo_editar:     module.comercio.venta + '/clientetipo/editar',
    wscomercioventaclientetipo_update:     module.comercio.venta + '/clientetipo/update',
    wscomercioventaclientetipo_show:       module.comercio.venta + '/clientetipo/show',
    wscomercioventaclientetipo_delete:     module.comercio.venta + '/clientetipo/delete',
    wscomercioventaclientetipo_reporte:    module.comercio.venta + '/clientetipo/reporte',
    wscomercioventaclientetipo_searchByID: module.comercio.venta + '/clientetipo/searchByID',

    wscomercioventacliente_index:      module.comercio.venta + '/cliente/index',
    wscomercioventacliente_create:     module.comercio.venta + '/cliente/create',
    wscomercioventacliente_store:      module.comercio.venta + '/cliente/store',
    wscomercioventacliente_editar:     module.comercio.venta + '/cliente/editar',
    wscomercioventacliente_update:     module.comercio.venta + '/cliente/update',
    wscomercioventacliente_show:       module.comercio.venta + '/cliente/show',
    wscomercioventacliente_delete:     module.comercio.venta + '/cliente/delete',
    wscomercioventacliente_reporte:    module.comercio.venta + '/cliente/reporte',
    wscomercioventacliente_searchByID: module.comercio.venta + '/cliente/searchByID',
    wscomercioventacliente_searchByNit: module.comercio.venta + '/cliente/searchByNit',

    wscomercioventacomisionventa_index:      module.comercio.venta + '/comisionventa/index',
    wscomercioventacomisionventa_create:     module.comercio.venta + '/comisionventa/create',
    wscomercioventacomisionventa_store:      module.comercio.venta + '/comisionventa/store',
    wscomercioventacomisionventa_editar:     module.comercio.venta + '/comisionventa/editar',
    wscomercioventacomisionventa_update:     module.comercio.venta + '/comisionventa/update',
    wscomercioventacomisionventa_show:       module.comercio.venta + '/comisionventa/show',
    wscomercioventacomisionventa_delete:     module.comercio.venta + '/comisionventa/delete',
    wscomercioventacomisionventa_reporte:    module.comercio.venta + '/comisionventa/reporte',
    wscomercioventacomisionventa_searchByID: module.comercio.venta + '/comisionventa/searchByID',

    wscomercioventavendedor_index:      module.comercio.venta + '/vendedor/index',
    wscomercioventavendedor_create:     module.comercio.venta + '/vendedor/create',
    wscomercioventavendedor_store:      module.comercio.venta + '/vendedor/store',
    wscomercioventavendedor_editar:     module.comercio.venta + '/vendedor/editar',
    wscomercioventavendedor_update:     module.comercio.venta + '/vendedor/update',
    wscomercioventavendedor_show:       module.comercio.venta + '/vendedor/show',
    wscomercioventavendedor_delete:     module.comercio.venta + '/vendedor/delete',
    wscomercioventavendedor_reporte:    module.comercio.venta + '/vendedor/reporte',
    wscomercioventavendedor_searchByID: module.comercio.venta + '/vendedor/searchByID',

    wscomercioventaactividadeconomica_index:      module.comercio.venta + '/actividadeconomica/index',
    wscomercioventaactividadeconomica_create:     module.comercio.venta + '/actividadeconomica/create',
    wscomercioventaactividadeconomica_store:      module.comercio.venta + '/actividadeconomica/store',
    wscomercioventaactividadeconomica_editar:     module.comercio.venta + '/actividadeconomica/editar',
    wscomercioventaactividadeconomica_update:     module.comercio.venta + '/actividadeconomica/update',
    wscomercioventaactividadeconomica_show:       module.comercio.venta + '/actividadeconomica/show',
    wscomercioventaactividadeconomica_delete:     module.comercio.venta + '/actividadeconomica/delete',
    wscomercioventaactividadeconomica_reporte:    module.comercio.venta + '/actividadeconomica/reporte',
    wscomercioventaactividadeconomica_searchByID: module.comercio.venta + '/actividadeconomica/searchByID',

    wscomercioventadosificacion_index:      module.comercio.venta + '/dosificacion/index',
    wscomercioventadosificacion_create:     module.comercio.venta + '/dosificacion/create',
    wscomercioventadosificacion_store:      module.comercio.venta + '/dosificacion/store',
    wscomercioventadosificacion_editar:     module.comercio.venta + '/dosificacion/editar',
    wscomercioventadosificacion_update:     module.comercio.venta + '/dosificacion/update',
    wscomercioventadosificacion_show:       module.comercio.venta + '/dosificacion/show',
    wscomercioventadosificacion_delete:     module.comercio.venta + '/dosificacion/delete',
    wscomercioventadosificacion_reporte:    module.comercio.venta + '/dosificacion/reporte',
    wscomercioventadosificacion_searchByID: module.comercio.venta + '/dosificacion/searchByID',

    wscomercioventanotaventa_index:      module.comercio.venta + '/notaventa/index',
    wscomercioventanotaventa_create:     module.comercio.venta + '/notaventa/create',
    wscomercioventanotaventa_store:      module.comercio.venta + '/notaventa/store',
    wscomercioventanotaventa_editar:     module.comercio.venta + '/notaventa/editar',
    wscomercioventanotaventa_update:     module.comercio.venta + '/notaventa/update',
    wscomercioventanotaventa_show:       module.comercio.venta + '/notaventa/show',
    wscomercioventanotaventa_delete:     module.comercio.venta + '/notaventa/delete',
    wscomercioventanotaventa_reporte:    module.comercio.venta + '/notaventa/reporte',
    wscomercioventanotaventa_searchByID: module.comercio.venta + '/notaventa/searchByID',



    wscomerciocompraproveedortipo_index:      module.comercio.compra + '/proveedortipo/index',
    wscomerciocompraproveedortipo_create:     module.comercio.compra + '/proveedortipo/create',
    wscomerciocompraproveedortipo_store:      module.comercio.compra + '/proveedortipo/store',
    wscomerciocompraproveedortipo_editar:     module.comercio.compra + '/proveedortipo/editar',
    wscomerciocompraproveedortipo_update:     module.comercio.compra + '/proveedortipo/update',
    wscomerciocompraproveedortipo_show:       module.comercio.compra + '/proveedortipo/show',
    wscomerciocompraproveedortipo_delete:     module.comercio.compra + '/proveedortipo/delete',
    wscomerciocompraproveedortipo_reporte:    module.comercio.compra + '/proveedortipo/reporte',
    wscomerciocompraproveedortipo_searchByID: module.comercio.compra + '/proveedortipo/searchByID',

    wscomerciocompraproveedorgrupo_index:      module.comercio.compra + '/proveedorgrupo/index',
    wscomerciocompraproveedorgrupo_create:     module.comercio.compra + '/proveedorgrupo/create',
    wscomerciocompraproveedorgrupo_store:      module.comercio.compra + '/proveedorgrupo/store',
    wscomerciocompraproveedorgrupo_editar:     module.comercio.compra + '/proveedorgrupo/editar',
    wscomerciocompraproveedorgrupo_update:     module.comercio.compra + '/proveedorgrupo/update',
    wscomerciocompraproveedorgrupo_show:       module.comercio.compra + '/proveedorgrupo/show',
    wscomerciocompraproveedorgrupo_delete:     module.comercio.compra + '/proveedorgrupo/delete',
    wscomerciocompraproveedorgrupo_reporte:    module.comercio.compra + '/proveedorgrupo/reporte',
    wscomerciocompraproveedorgrupo_searchByID: module.comercio.compra + '/proveedorgrupo/searchByID',

    wscomerciocompraproveedorcargo_index:      module.comercio.compra + '/proveedorcargo/index',
    wscomerciocompraproveedorcargo_create:     module.comercio.compra + '/proveedorcargo/create',
    wscomerciocompraproveedorcargo_store:      module.comercio.compra + '/proveedorcargo/store',
    wscomerciocompraproveedorcargo_editar:     module.comercio.compra + '/proveedorcargo/editar',
    wscomerciocompraproveedorcargo_update:     module.comercio.compra + '/proveedorcargo/update',
    wscomerciocompraproveedorcargo_show:       module.comercio.compra + '/proveedorcargo/show',
    wscomerciocompraproveedorcargo_delete:     module.comercio.compra + '/proveedorcargo/delete',
    wscomerciocompraproveedorcargo_reporte:    module.comercio.compra + '/proveedorcargo/reporte',
    wscomerciocompraproveedorcargo_searchByID: module.comercio.compra + '/proveedorcargo/searchByID',

    wscomerciocompraproveedor_index:      module.comercio.compra + '/proveedor/index',
    wscomerciocompraproveedor_create:     module.comercio.compra + '/proveedor/create',
    wscomerciocompraproveedor_store:      module.comercio.compra + '/proveedor/store',
    wscomerciocompraproveedor_editar:     module.comercio.compra + '/proveedor/editar',
    wscomerciocompraproveedor_update:     module.comercio.compra + '/proveedor/update',
    wscomerciocompraproveedor_show:       module.comercio.compra + '/proveedor/show',
    wscomerciocompraproveedor_delete:     module.comercio.compra + '/proveedor/delete',
    wscomerciocompraproveedor_reporte:    module.comercio.compra + '/proveedor/reporte',
    wscomerciocompraproveedor_searchByID: module.comercio.compra + '/proveedor/searchByID',

    wscomerciocompraconceptocompra_index:      module.comercio.compra + '/conceptocompra/index',
    wscomerciocompraconceptocompra_create:     module.comercio.compra + '/conceptocompra/create',
    wscomerciocompraconceptocompra_store:      module.comercio.compra + '/conceptocompra/store',
    wscomerciocompraconceptocompra_editar:     module.comercio.compra + '/conceptocompra/editar',
    wscomerciocompraconceptocompra_update:     module.comercio.compra + '/conceptocompra/update',
    wscomerciocompraconceptocompra_show:       module.comercio.compra + '/conceptocompra/show',
    wscomerciocompraconceptocompra_delete:     module.comercio.compra + '/conceptocompra/delete',
    wscomerciocompraconceptocompra_reporte:    module.comercio.compra + '/conceptocompra/reporte',
    wscomerciocompraconceptocompra_searchByID: module.comercio.compra + '/conceptocompra/searchByID',

    wscomerciocomprasolicitudcompra_index:      module.comercio.compra + '/solicitudcompra/index',
    wscomerciocomprasolicitudcompra_create:     module.comercio.compra + '/solicitudcompra/create',
    wscomerciocomprasolicitudcompra_store:      module.comercio.compra + '/solicitudcompra/store',
    wscomerciocomprasolicitudcompra_editar:     module.comercio.compra + '/solicitudcompra/editar',
    wscomerciocomprasolicitudcompra_update:     module.comercio.compra + '/solicitudcompra/update',
    wscomerciocomprasolicitudcompra_show:       module.comercio.compra + '/solicitudcompra/show',
    wscomerciocomprasolicitudcompra_delete:     module.comercio.compra + '/solicitudcompra/delete',
    wscomerciocomprasolicitudcompra_reporte:    module.comercio.compra + '/solicitudcompra/reporte',
    wscomerciocomprasolicitudcompra_searchByID: module.comercio.compra + '/solicitudcompra/searchByID',

    wscomerciocompraordencompra_index:      module.comercio.compra + '/ordencompra/index',
    wscomerciocompraordencompra_create:     module.comercio.compra + '/ordencompra/create',
    wscomerciocompraordencompra_store:      module.comercio.compra + '/ordencompra/store',
    wscomerciocompraordencompra_editar:     module.comercio.compra + '/ordencompra/editar',
    wscomerciocompraordencompra_update:     module.comercio.compra + '/ordencompra/update',
    wscomerciocompraordencompra_show:       module.comercio.compra + '/ordencompra/show',
    wscomerciocompraordencompra_delete:     module.comercio.compra + '/ordencompra/delete',
    wscomerciocompraordencompra_reporte:    module.comercio.compra + '/ordencompra/reporte',
    wscomerciocompraordencompra_searchByID: module.comercio.compra + '/ordencompra/searchByID',

    wscomerciocompranotacompra_index:      module.comercio.compra + '/notacompra/index',
    wscomerciocompranotacompra_create:     module.comercio.compra + '/notacompra/create',
    wscomerciocompranotacompra_store:      module.comercio.compra + '/notacompra/store',
    wscomerciocompranotacompra_editar:     module.comercio.compra + '/notacompra/editar',
    wscomerciocompranotacompra_update:     module.comercio.compra + '/notacompra/update',
    wscomerciocompranotacompra_show:       module.comercio.compra + '/notacompra/show',
    wscomerciocompranotacompra_delete:     module.comercio.compra + '/notacompra/delete',
    wscomerciocompranotacompra_reporte:    module.comercio.compra + '/notacompra/reporte',
    wscomerciocompranotacompra_searchByID: module.comercio.compra + '/notacompra/searchByID',

    wscomerciocompradevolucioncompra_index:      module.comercio.compra + '/devolucioncompra/index',
    wscomerciocompradevolucioncompra_create:     module.comercio.compra + '/devolucioncompra/create',
    wscomerciocompradevolucioncompra_store:      module.comercio.compra + '/devolucioncompra/store',
    wscomerciocompradevolucioncompra_editar:     module.comercio.compra + '/devolucioncompra/editar',
    wscomerciocompradevolucioncompra_update:     module.comercio.compra + '/devolucioncompra/update',
    wscomerciocompradevolucioncompra_show:       module.comercio.compra + '/devolucioncompra/show',
    wscomerciocompradevolucioncompra_delete:     module.comercio.compra + '/devolucioncompra/delete',
    wscomerciocompradevolucioncompra_reporte:    module.comercio.compra + '/devolucioncompra/reporte',
    wscomerciocompradevolucioncompra_searchByID: module.comercio.compra + '/devolucioncompra/searchByID',

    wscomerciocomprainformecompra_notacomprageneral: module.comercio.compra + '/informecompra/notacomprageneral',

};

export default webservices ;
