
const moduleInventario = {

    ciudadclasificacion_setLimpiar:   '[Ciudad Clasificacion] Set Limpiar',
    ciudadclasificacion_onChange:     '[Ciudad Clasificacion] On Change',
    ciudadclasificacion_setImprimir:  '[Ciudad Clasificacion] Set Imprimir',
    ciudadclasificacion_setState:     '[Ciudad Clasificacion] Set Ciudad Clasificacion',
    ciudadclasificacion_onCreate:     '[Ciudad Clasificacion] on Create',
    ciudadclasificacion_onFocus:      '[Ciudad Clasificacion] On Focus',
    ciudadclasificacion_offFocus:     '[Ciudad Clasificacion] Off Focus',

    ciudad_setLimpiar:   '[Ciudad] Set Limpiar',
    ciudad_setLoad:      '[Ciudad] Set Load',
    ciudad_onChange:     '[Ciudad] On Change',
    ciudad_setImprimir:  '[Ciudad] Set Imprimir',
    ciudad_setState:     '[Ciudad] Set Ciudad',
    ciudad_onCreate:     '[Ciudad] on Create',
    ciudad_onEditar:     '[Ciudad] on Editar',
    ciudad_onShow:     '[Ciudad] on Show',
    ciudad_onFocus:      '[Ciudad] On Focus',
    ciudad_offFocus:     '[Ciudad] Off Focus',

    productotipo_setLimpiar:   '[Producto Tipo] Set Limpiar',
    productotipo_onChange:     '[Producto Tipo] On Change',
    productotipo_setImprimir:  '[Producto Tipo] Set Imprimir',
    productotipo_setState:     '[Producto Tipo] Set Producto Tipo',
    productotipo_onCreate:     '[Producto Tipo] on Create',
    productotipo_onFocus:      '[Producto Tipo] On Focus',
    productotipo_offFocus:     '[Producto Tipo] Off Focus',

    productomarca_setLimpiar:   '[Producto Marca] Set Limpiar',
    productomarca_onChange:     '[Producto Marca] On Change',
    productomarca_setImprimir:  '[Producto Marca] Set Imprimir',
    productomarca_setState:     '[Producto Marca] Set Producto Marca',
    productomarca_onCreate:     '[Producto Marca] on Create',
    productomarca_onFocus:      '[Producto Marca] On Focus',
    productomarca_offFocus:     '[Producto Marca] Off Focus',

    productosubgrupo_setLimpiar:   '[Producto Sub Grupo] Set Limpiar',
    productosubgrupo_onChange:     '[Producto Sub Grupo] On Change',
    productosubgrupo_setImprimir:  '[Producto Sub  Grupo] Set Imprimir',
    productosubgrupo_setState:     '[Producto Sub Grupo] Set Producto Sub Grupo',
    productosubgrupo_onCreate:     '[Producto Sub Grupo] on Create',
    productosubgrupo_onFocus:      '[Producto Sub Grupo] On Focus',
    productosubgrupo_offFocus:     '[Producto Sub Grupo] Off Focus',

    productogrupo_setLimpiar:   '[Producto Grupo] Set Limpiar',
    productogrupo_onChange:     '[Producto Grupo] On Change',
    productogrupo_setImprimir:  '[Producto Grupo] Set Imprimir',
    productogrupo_setState:     '[Producto Grupo] Set Producto Grupo',
    productogrupo_onCreate:     '[Producto Grupo] on Create',
    productogrupo_onFocus:      '[Producto Grupo] On Focus',
    productogrupo_offFocus:     '[Producto Grupo] Off Focus',

    categoria_setLimpiar:   '[Categoria] Set Limpiar',
    categoria_onChange:     '[Categoria] On Change',
    categoria_setImprimir:  '[Categoria] Set Imprimir',
    categoria_setState:     '[Categoria] Set Categoria',
    categoria_onCreate:     '[Categoria] on Create',
    categoria_onFocus:      '[Categoria] On Focus',
    categoria_offFocus:     '[Categoria] Off Focus',

    unidadmedida_setLimpiar:   '[Unidad Medida] Set Limpiar',
    unidadmedida_onChange:     '[Unidad Medida] On Change',
    unidadmedida_setImprimir:  '[Unidad Medida] Set Imprimir',
    unidadmedida_setState:     '[Unidad Medida] Set Unidad Medida',
    unidadmedida_onCreate:     '[Unidad Medida] on Create',
    unidadmedida_onFocus:      '[Unidad Medida] On Focus',
    unidadmedida_offFocus:     '[Unidad Medida] Off Focus',

    conceptoinventario_setLimpiar:   '[Concepto Inventario] Set Limpiar',
    conceptoinventario_setLoad:      '[Concepto Inventario] Set Load',
    conceptoinventario_onChange:     '[Concepto Inventario] On Change',
    conceptoinventario_setImprimir:  '[Concepto Inventario] Set Imprimir',
    conceptoinventario_setState:     '[Concepto Inventario] Set Concepto Inventario',
    conceptoinventario_onCreate:     '[Concepto Inventario] on Create',
    conceptoinventario_onEditar:     '[Concepto Inventario] on Editar',
    conceptoinventario_onShow:       '[Concepto Inventario] on Show',
    conceptoinventario_onFocus:      '[Concepto Inventario] On Focus',
    conceptoinventario_offFocus:     '[Concepto Inventario] Off Focus',

    seccioninventario_setLimpiar:   '[Sección Inventario] Set Limpiar',
    seccioninventario_setLoad:      '[Sección Inventario] Set Load',
    seccioninventario_onChange:     '[Sección Inventario] On Change',
    seccioninventario_setImprimir:  '[Sección Inventario] Set Imprimir',
    seccioninventario_setState:     '[Sección Inventario] Set Sección Inventario',
    seccioninventario_onCreate:     '[Sección Inventario] on Create',
    seccioninventario_onEditar:     '[Sección Inventario] on Editar',
    seccioninventario_onShow:       '[Sección Inventario] on Show',
    seccioninventario_onFocus:      '[Sección Inventario] On Focus',
    seccioninventario_offFocus:     '[Sección Inventario] Off Focus',

    almacen_setLimpiar:   '[Álmacen] Set Limpiar',
    almacen_setLoad:      '[Álmacen] Set Load',
    almacen_onChange:     '[Álmacen] On Change',
    almacen_setImprimir:  '[Álmacen] Set Imprimir',
    almacen_setState:     '[Álmacen] Set Álmacen',
    almacen_onCreate:     '[Álmacen] on Create',
    almacen_onEditar:     '[Álmacen] on Editar',
    almacen_onShow:       '[Álmacen] on Show',
    almacen_onFocus:      '[Álmacen] On Focus',
    almacen_offFocus:     '[Álmacen] Off Focus',


    notaingreso_setLimpiar:   '[Nota Ingreso] Set Limpiar',
    notaingreso_setLoad:      '[Nota Ingreso] Set Load',
    notaingreso_onChange:     '[Nota Ingreso] On Change',
    notaingreso_setImprimir:  '[Nota Ingreso] Set Imprimir',
    notaingreso_setState:     '[Nota Ingreso] Set Nota Ingreso',
    notaingreso_onCreate:     '[Nota Ingreso] on Create',
    notaingreso_onEditar:     '[Nota Ingreso] on Editar',
    notaingreso_onShow:       '[Nota Ingreso] on Show',
    notaingreso_onFocus:      '[Nota Ingreso] On Focus',
    notaingreso_offFocus:     '[Nota Ingreso] Off Focus',

    ciudad_setArray: '[Ciudad] Set Array',
};

const moduleVenta = {
    unionsucursal_setLimpiar:   '[Union Sucursal] Set Limpiar',
    unionsucursal_setLoad:      '[Union Sucursal] Set Load',
    unionsucursal_onChange:     '[Union Sucursal] On Change',
    unionsucursal_setImprimir:  '[Union Sucursal] Set Imprimir',
    unionsucursal_setState:     '[Union Sucursal] Set Union Sucursal',
    unionsucursal_onCreate:     '[Union Sucursal] on Create',
    unionsucursal_onEditar:     '[Union Sucursal] on Editar',
    unionsucursal_onShow:       '[Union Sucursal] on Show',
    unionsucursal_onFocus:      '[Union Sucursal] On Focus',
    unionsucursal_offFocus:     '[Union Sucursal] Off Focus',

    sucursal_setLimpiar:   '[Sucursal] Set Limpiar',
    sucursal_setLoad:      '[Sucursal] Set Load',
    sucursal_onChange:     '[Sucursal] On Change',
    sucursal_setImprimir:  '[Sucursal] Set Imprimir',
    sucursal_setState:     '[Sucursal] Set Sucursal',
    sucursal_onCreate:     '[Sucursal] on Create',
    sucursal_onEditar:     '[Sucursal] on Editar',
    sucursal_onShow:       '[Sucursal] on Show',
    sucursal_onFocus:      '[Sucursal] On Focus',
    sucursal_offFocus:     '[Sucursal] Off Focus',

    listaprecio_setLimpiar:   '[Lista Precio] Set Limpiar',
    listaprecio_setLoad:      '[Lista Precio] Set Load',
    listaprecio_onChange:     '[Lista Precio] On Change',
    listaprecio_setImprimir:  '[Lista Precio] Set Imprimir',
    listaprecio_setState:     '[Lista Precio] Set [Lista Precio',
    listaprecio_onCreate:     '[Lista Precio] on Create',
    listaprecio_onEditar:     '[Lista Precio] on Editar',
    listaprecio_onShow:       '[Lista Precio] on Show',
    listaprecio_onFocus:      '[Lista Precio] On Focus',
    listaprecio_offFocus:     '[Lista Precio] Off Focus',

    clientetipo_setLimpiar:   '[Cliente Tipo] Set Limpiar',
    clientetipo_setLoad:      '[Cliente Tipo] Set Load',
    clientetipo_onChange:     '[Cliente Tipo] On Change',
    clientetipo_setImprimir:  '[Cliente Tipo] Set Imprimir',
    clientetipo_setState:     '[Cliente Tipo] Set [Cliente Tipo',
    clientetipo_onCreate:     '[Cliente Tipo] on Create',
    clientetipo_onEditar:     '[Cliente Tipo] on Editar',
    clientetipo_onShow:       '[Cliente Tipo] on Show',
    clientetipo_onFocus:      '[Cliente Tipo] On Focus',
    clientetipo_offFocus:     '[Cliente Tipo] Off Focus',

    cliente_setLimpiar:   '[Cliente] Set Limpiar',
    cliente_setLoad:      '[Cliente] Set Load',
    cliente_onChange:     '[Cliente] On Change',
    cliente_setImprimir:  '[Cliente] Set Imprimir',
    cliente_setState:     '[Cliente] Set [Cliente',
    cliente_onCreate:     '[Cliente] on Create',
    cliente_onEditar:     '[Cliente] on Editar',
    cliente_onShow:       '[Cliente] on Show',
    cliente_onFocus:      '[Cliente] On Focus',
    cliente_offFocus:     '[Cliente] Off Focus',

    conceptoventa_setLimpiar:   '[Concepto Venta] Set Limpiar',
    conceptoventa_setLoad:      '[Concepto Venta] Set Load',
    conceptoventa_onChange:     '[Concepto Venta] On Change',
    conceptoventa_setImprimir:  '[Concepto Venta] Set Imprimir',
    conceptoventa_setState:     '[Concepto Venta] Set [Concepto Venta',
    conceptoventa_onCreate:     '[Concepto Venta] on Create',
    conceptoventa_onEditar:     '[Concepto Venta] on Editar',
    conceptoventa_onShow:       '[Concepto Venta] on Show',
    conceptoventa_onFocus:      '[Concepto Venta] On Focus',
    conceptoventa_offFocus:     '[Concepto Venta] Off Focus',

    producto_setLimpiar:   '[Producto] Set Limpiar',
    producto_setLoad:      '[Producto] Set Load',
    producto_onChange:     '[Producto] On Change',
    producto_setImprimir:  '[Producto] Set Imprimir',
    producto_setState:     '[Producto] Set Producto',
    producto_onCreate:     '[Producto] on Create',
    producto_onEditar:     '[Producto] on Editar',
    producto_onShow:       '[Producto] on Show',
    producto_onFocus:      '[Producto] On Focus',
    producto_offFocus:     '[Producto] Off Focus',

};

const moduleCompra = {
    proveedortipo_setLimpiar:   '[Tipo Proveedor] Set Limpiar',
    proveedortipo_setLoad:      '[Tipo Proveedor] Set Load',
    proveedortipo_onChange:     '[Tipo Proveedor] On Change',
    proveedortipo_setImprimir:  '[Tipo Proveedor] Set Imprimir',
    proveedortipo_setState:     '[Tipo Proveedor] Set Tipo Proveedor',
    proveedortipo_onCreate:     '[Tipo Proveedor] on Create',
    proveedortipo_onEditar:     '[Tipo Proveedor] on Editar',
    proveedortipo_onShow:       '[Tipo Proveedor] on Show',
    proveedortipo_onFocus:      '[Tipo Proveedor] On Focus',
    proveedortipo_offFocus:     '[Tipo Proveedor] Off Focus',

    proveedorgrupo_setLimpiar:   '[Grupo Proveedor] Set Limpiar',
    proveedorgrupo_setLoad:      '[Grupo Proveedor] Set Load',
    proveedorgrupo_onChange:     '[Grupo Proveedor] On Change',
    proveedorgrupo_setImprimir:  '[Grupo Proveedor] Set Imprimir',
    proveedorgrupo_setState:     '[Grupo Proveedor] Set Grupo Proveedor',
    proveedorgrupo_onCreate:     '[Grupo Proveedor] on Create',
    proveedorgrupo_onEditar:     '[Grupo Proveedor] on Editar',
    proveedorgrupo_onShow:       '[Grupo Proveedor] on Show',
    proveedorgrupo_onFocus:      '[Grupo Proveedor] On Focus',
    proveedorgrupo_offFocus:     '[Grupo Proveedor] Off Focus',

    proveedorcargo_setLimpiar:   '[Cargo Proveedor] Set Limpiar',
    proveedorcargo_setLoad:      '[Cargo Proveedor] Set Load',
    proveedorcargo_onChange:     '[Cargo Proveedor] On Change',
    proveedorcargo_setImprimir:  '[Cargo Proveedor] Set Imprimir',
    proveedorcargo_setState:     '[Cargo Proveedor] Set Cargo Proveedor',
    proveedorcargo_onCreate:     '[Cargo Proveedor] on Create',
    proveedorcargo_onEditar:     '[Cargo Proveedor] on Editar',
    proveedorcargo_onShow:       '[Cargo Proveedor] on Show',
    proveedorcargo_onFocus:      '[Cargo Proveedor] On Focus',
    proveedorcargo_offFocus:     '[Cargo Proveedor] Off Focus',

    proveedor_setLimpiar:   '[Proveedor] Set Limpiar',
    proveedor_setLoad:      '[Proveedor] Set Load',
    proveedor_onChange:     '[Proveedor] On Change',
    proveedor_setImprimir:  '[Proveedor] Set Imprimir',
    proveedor_setState:     '[Proveedor] Set Proveedor',
    proveedor_onCreate:     '[Proveedor] on Create',
    proveedor_onEditar:     '[Proveedor] on Editar',
    proveedor_onShow:       '[Proveedor] on Show',
    proveedor_onFocus:      '[Proveedor] On Focus',
    proveedor_offFocus:     '[Proveedor] Off Focus',

    conceptocompra_setLimpiar:   '[Concepto Compra] Set Limpiar',
    conceptocompra_setLoad:      '[Concepto Compra] Set Load',
    conceptocompra_onChange:     '[Concepto Compra] On Change',
    conceptocompra_setImprimir:  '[Concepto Compra] Set Imprimir',
    conceptocompra_setState:     '[Concepto Compra] Set Concepto Compra',
    conceptocompra_onCreate:     '[Concepto Compra] on Create',
    conceptocompra_onEditar:     '[Concepto Compra] on Editar',
    conceptocompra_onShow:       '[Concepto Compra] on Show',
    conceptocompra_onFocus:      '[Concepto Compra] On Focus',
    conceptocompra_offFocus:     '[Concepto Compra] Off Focus',

    solicitudcompra_setLimpiar:   '[Solicitud Compra] Set Limpiar',
    solicitudcompra_setLoad:      '[Solicitud Compra] Set Load',
    solicitudcompra_onChange:     '[Solicitud Compra] On Change',
    solicitudcompra_setImprimir:  '[Solicitud Compra] Set Imprimir',
    solicitudcompra_setState:     '[Solicitud Compra] Set Solicitud Compra',
    solicitudcompra_onCreate:     '[Solicitud Compra] on Create',
    solicitudcompra_onEditar:     '[Solicitud Compra] on Editar',
    solicitudcompra_onShow:       '[Solicitud Compra] on Show',
    solicitudcompra_onFocus:      '[Solicitud Compra] On Focus',
    solicitudcompra_offFocus:     '[Solicitud Compra] Off Focus',

    ordencompra_setLimpiar:   '[Orden Compra] Set Limpiar',
    ordencompra_setLoad:      '[Orden Compra] Set Load',
    ordencompra_onChange:     '[Orden Compra] On Change',
    ordencompra_setImprimir:  '[Orden Compra] Set Imprimir',
    ordencompra_setState:     '[Orden Compra] Set Orden Compra',
    ordencompra_onCreate:     '[Orden Compra] on Create',
    ordencompra_onEditar:     '[Orden Compra] on Editar',
    ordencompra_onShow:       '[Orden Compra] on Show',
    ordencompra_onFocus:      '[Orden Compra] On Focus',
    ordencompra_offFocus:     '[Orden Compra] Off Focus',

    notacompra_setLimpiar:   '[Nota Compra] Set Limpiar',
    notacompra_setLoad:      '[Nota Compra] Set Load',
    notacompra_onChange:     '[Nota Compra] On Change',
    notacompra_setImprimir:  '[Nota Compra] Set Imprimir',
    notacompra_setState:     '[Nota Compra] Set Nota Compra',
    notacompra_onCreate:     '[Nota Compra] on Create',
    notacompra_onEditar:     '[Nota Compra] on Editar',
    notacompra_onShow:       '[Nota Compra] on Show',
    notacompra_onFocus:      '[Nota Compra] On Focus',
    notacompra_offFocus:     '[Nota Compra] Off Focus',

    devolucioncompra_setLimpiar:   '[Devolución Compra] Set Limpiar',
    devolucioncompra_setLoad:      '[Devolución Compra] Set Load',
    devolucioncompra_onChange:     '[Devolución Compra] On Change',
    devolucioncompra_setImprimir:  '[Devolución Compra] Set Imprimir',
    devolucioncompra_setState:     '[Devolución Compra] Set Devolución Compra',
    devolucioncompra_onCreate:     '[Devolución Compra] on Create',
    devolucioncompra_onEditar:     '[Devolución Compra] on Editar',
    devolucioncompra_onShow:       '[Devolución Compra] on Show',
    devolucioncompra_onFocus:      '[Devolución Compra] On Focus',
    devolucioncompra_offFocus:     '[Devolución Compra] Off Focus',

    informecompra_setLimpiar:   '[Informe Compra] Set Limpiar',
    informecompra_setInit:      '[Informe Compra] Set Init',
    informecompra_setLoad:      '[Informe Compra] Set Load',
    informecompra_onChange:     '[Informe Compra] On Change',
    informecompra_setImprimir:  '[Informe Compra] Set Imprimir',
};

const config = {
    showNotaIngreso: '[Visible] show Nota Ingreso',
    hideNotaIngreso: '[Visible] hide Nota Ingreso',

    showNotaSalida: '[Visible] show Nota Salida',
    hideNotaSalida: '[Visible] hide Nota Salida',

    showNotaTraspaso: '[Visible] show Nota Trapaso',
    hideNotaTraspaso: '[Visible] hide Nota Trapaso',

    showMarca: '[Visible] show Marca',
    hideMarca: '[Visible] hide Marca',

    showProducto: '[Visible] hide Producto',
    hideProducto: '[Visible] hide Producto',

    showCiudad: '[Visible] show Ciudad',
    hideCiudad: '[Visible] hide Ciudad',

    showCiudadClasificacion: '[Visible] show Ciudad Clasificacion',
    hideCiudadClasificacion: '[Visible] hide Ciudad Clasificacion',

    setDisabledLimpiar: '[Disabled] Disabled Limpiar',
    setDisabledCreate:  '[Disabled] Set Disabled Create',
    setDisabledEditar:  '[Disabled] Set Disabled Editar',
    setDisabledAction:  '[Disabled] Set Disabled Action',

    setLoading:    '[Loading] Set Loding',
    removeLoading: '[Loading] Remove Loading',

    setPagination:   '[Pagination] Set Pagination',
    removePagintion: '[Pagination] Remove Pagination',

    setPrintOption:   '[Print Option] Set Print Option',
    resetPrintOption: '[Print Option] Reset Print Option',

    setArchivoOption:   '[Archivo Option] Set Archivo Option',
    resetArchivoOption: '[Archivo Option] Reset Archivo Option',

};

// let sistema = {};
// sistema = Object.assign( sistema, moduleInventario );
// sistema = Object.assign( sistema, visible );

export const Strings = Object.assign( moduleCompra, Object.assign( Object.assign( moduleInventario, moduleVenta ), config ) );
